### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by JzKUO** [OYsun/vscode-VueHelper#22]
what happen?
Is there anyone else have the same problem?

`
/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
[Info  - 1:51:00 AM] Connection to server got closed. Server will restart.
/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
[Info  - 1:51:02 AM] Connection to server got closed. Server will restart.
/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
[Info  - 1:51:03 AM] Connection to server got closed. Server will restart.
/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
[Info  - 1:51:05 AM] Connection to server got closed. Server will restart.
/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/Users/JzKUO/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
[Error - 1:51:07 AM] Connection to server got closed. Server will not be restarted.
`

**Comment by w550** [comment]
+1

**Comment by thatdoorsajar** [comment]
+1
